name: todo
description: "Simple todo app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  toastification: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          style: italic
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/todo.png"

flutter_native_splash:
  color: "#2C2D31"
  image: assets/images/todo.png

  android_12:
    image: assets/images/todo.png
    color: "#2C2D31"
