name: todo
description: "Simple todo app."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          style: italic
          weight: 700


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/todo.png"